<?php

namespace App\Mail;

use App\Models\Order;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Contracts\Queue\ShouldQueue;

class OrderAdminMail extends Mailable
{
    use Queueable, SerializesModels;

    public $order;

    public function subject($subject)
    {
        return parent::subject('A new Order Has Been Placed'); // TODO: Change the autogenerated stub
    }

    /**
     * Create a new message instance.
     *
     * @param $orderno
     */
    public function __construct($orderno)
    {
        $this->order = Order::where('id',$orderno)->first();
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->markdown('emails.order-admin');
    }
}
